HW done with tests passed
RomanAVolodin/java-shareit pull request #2
Opened 2022-08-31 12:30 UTC by RomanAVolodin

2022-09-01 06:58 UTC, Frilock requested changes
Добрый день, в целом все ок, оставил пару мелких комментариев.

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (item.getOwnerId().equals(userId)) {
По моему ownerId не not null поле, поэтому лучше использовать null safe equals - Objects.equals(v1, v2), чтобы случайно NPE не получить

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED) && approved) {
Не знаю, ставили Вы или нет, но продублирую. Советую поставить плагин sonarlint - статический анализатор кода, дает не мало рекомендаций по улучшению кода.

Кроме того, вообще enum поля лучше сравнивать через обычные операторы != и ==, работать будет в любом случае, но данный оператор как минимум быстрее

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        var user = userRepository.findById(userId).orElseThrow(
А зачем тут запрос пользователя? Как минимум возвращаемое значение не используется:

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private List<BookingResponseDto> processBookingsForBooker(Long userId, BookingState state) {
Вообще мб стоит из двух методов один сделать? А передавать внутрь параметр - где искать
На Ваше усмотрение

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateDto.java
> +    @Size(max = SIZE_COMMENT_TEXT, message = "Описание не должно превышать" + SIZE_COMMENT_TEXT + "символов")
message = "Описание не должно превышать" + SIZE_COMMENT_TEXT + "символов" - не сольется ?

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        List<Booking> resultBookings = new ArrayList<>();
Можно не делать new ArrayList, у Вас в каждом блоке он инициализируется

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Setter
Можно Data сразу вешать, там еще equalsAndHashCode добавится только.

2022-09-01 06:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +// 		Если это не убрать, то тесты не проходят. Ужас!
1. Закомментированный код не оставляйте
2. А почему не проходят?)) Может ошибка у Вас где то

2022-09-01 06:58 UTC, Frilock commented on src/main/resources/application.properties
>  spring.datasource.driverClassName=org.h2.Driver
Пара конфигов дублируется для ДБ

2022-09-02 07:16 UTC, RomanAVolodin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        var user = userRepository.findById(userId).orElseThrow(
Проверка существования пользователя

2022-09-02 08:00 UTC, RomanAVolodin commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Setter
Где то читал, что @Entity и @Data вместе не рекомендуется.

2022-09-02 08:04 UTC, RomanAVolodin commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +// 		Если это не убрать, то тесты не проходят. Ужас!
В том то и весь ужас.
Я проверяю наличие пользователя, если его нет, кидаю исключение, что логично
А тесты требуют вот такой работы:
- создают пользователя и проверяют его id == 1
- создают пользователя с существующим email, ожидают что мы не додумаемся до проверки на уровне Java и стучатся в базу. База инкрементирует id и кидает исключение.
- следующий тест создает пользователя и проверяет его id == 3.
Т.е. если я проверяю в коде наличие пользователя, то id второго созданного будет 2 и тесты не проходят.

Вот так и вся работа. Код пишу 1-2 часа, и потом 3-4 дня пытаюсь понять чего хотят тесты.

2022-09-02 08:10 UTC, RomanAVolodin commented on src/main/resources/application.properties
>  spring.datasource.driverClassName=org.h2.Driver
Подчключил postgres базу для dev окружения, а для ci, test база в памяти (это уже было в репозитории).

2022-09-02 08:15 UTC, RomanAVolodin commented
Исправил все замечания и прокомментировал.

2022-09-03 07:39 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +// 		Если это не убрать, то тесты не проходят. Ужас!
Зато сразу с TDD познакомились)))

2022-09-03 07:40 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Setter
Странно, не слышал о таком, хотя все возможно)

2022-09-03 07:41 UTC, Frilock approved these changes
Принято

2022-09-17 18:23 UTC, merged